### ISSUE TITLE
Fueltype is not populated

### ISSUE THREAD

**Issue by KoenVerbeeck** [Azure-Player/Real-Time-Data-Simulator#5]
There seems to be an issue with the FuelType column, which always has the value "{{FuelType(MessageIndex)}}"

![image](https://github.com/Azure-Player/Real-Time-Data-Simulator/assets/7213731/14110309-2dd7-4c7f-bad0-098c9e725001)

**Comment by thedaxshepherd** [comment]
This code causes an error due to the index for the array going beyond the bounds if you set the number of messages to 20 or more.

![Error_20Messages](https://github.com/Azure-Player/Real-Time-Data-Simulator/assets/60486315/4586e16f-67ec-4894-bfd8-f98f305bd211)

Below are two methods I put in place so that I could continue testing with more than 20 messages. My theory on why MessageIndex was being used to select the fuel type was that eventually one of each fuel type would be represented in the data set. I tried to honor that intention. 

```c#
  if (key == "FuelType(MessageIndex)")
  {
      String[] arr = val.Split("|");

      //int i = rnd.Next(0, arr.Length); // if goal is to have random fuel type, uncomment this
      int i = msgIndex % arr.Length; // if goal is to iterate through fuel types, uncomment this
      val = arr[i];

      //val = arr[msgIndex]; // Causes an out of bounds error at 20 messages
  }
```

**Comment by NowinskiK** [comment]
Feel free to prepare PR - I'm happy to accept it and merge.
